name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.SECRET_KEY}}
          aws-region: ${{ secrets.REGION_NAME}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERID}}
          password: ${{ secrets.DOCKERPASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: graulwar/netflix-clone-docker-project:latest  # Replace with your Docker Hub repo and image tag

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy to EKS
        run: |
          aws eks --region ${{ secrets.REGION_NAME }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
          helm upgrade --install netflix-clone ./charts/netflix-clone --set image.repository=graulwar/netflix-clone-docker-project,image.tag=latest  # Adjust for your Helm chart and image
